name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: pip install -r scripts/requirements.txt
      - run: python -m pytest tests/
      - run: python src/main.py --model yolov8n.pt --lang english
